export const currencyOptions = [
    { value: "Afghan Afghani (AFN)", label: "Afghan Afghani (AFN)" },
    { value: "Albanian Lek (ALL)", label: "Albanian Lek (ALL)" },
    { value: "Algerian Dinar (DZD)", label: "Algerian Dinar (DZD)" },
    { value: "Angolan Kwanza (AOA)", label: "Angolan Kwanza (AOA)" },
    { value: "Argentine Peso (ARS)", label: "Argentine Peso (ARS)" },
    { value: "Armenian Dram (AMD)", label: "Armenian Dram (AMD)" },
    { value: "Aruban Florin (AWG)", label: "Aruban Florin (AWG)" },
    { value: "Australian Dollar (AUD)", label: "Australian Dollar (AUD)" },
    { value: "Azerbaijani Manat (AZN)", label: "Azerbaijani Manat (AZN)" },
    { value: "Bahamian Dollar (BSD)", label: "Bahamian Dollar (BSD)" },
    { value: "Bahraini Dinar (BHD)", label: "Bahraini Dinar (BHD)" },
    { value: "Bangladeshi Taka (BDT)", label: "Bangladeshi Taka (BDT)" },
    { value: "Barbadian Dollar (BBD)", label: "Barbadian Dollar (BBD)" },
    { value: "Belarusian Ruble (BYN)", label: "Belarusian Ruble (BYN)" },
    { value: "Belize Dollar (BZD)", label: "Belize Dollar (BZD)" },
    { value: "Bermudan Dollar (BMD)", label: "Bermudan Dollar (BMD)" },
    { value: "Bhutanese Ngultrum (BTN)", label: "Bhutanese Ngultrum (BTN)" },
    { value: "Bolivian Boliviano (BOB)", label: "Bolivian Boliviano (BOB)" },
    { value: "Bosnia-Herzegovina Convertible Mark (BAM)", label: "Bosnia-Herzegovina Convertible Mark (BAM)" },
    { value: "Botswanan Pula (BWP)", label: "Botswanan Pula (BWP)" },
    { value: "Brazilian Real (BRL)", label: "Brazilian Real (BRL)" },
    { value: "British Pound (GBP)", label: "British Pound (GBP)" },
    { value: "Brunei Dollar (BND)", label: "Brunei Dollar (BND)" },
    { value: "Bulgarian Lev (BGN)", label: "Bulgarian Lev (BGN)" },
    { value: "Burundian Franc (BIF)", label: "Burundian Franc (BIF)" },
    { value: "Cambodian Riel (KHR)", label: "Cambodian Riel (KHR)" },
    { value: "Canadian Dollar (CAD)", label: "Canadian Dollar (CAD)" },
    { value: "Cape Verdean Escudo (CVE)", label: "Cape Verdean Escudo (CVE)" },
    { value: "Central African CFA Franc (XAF)", label: "Central African CFA Franc (XAF)" },
    { value: "Chilean Peso (CLP)", label: "Chilean Peso (CLP)" },
    { value: "Chinese Yuan (CNY)", label: "Chinese Yuan (CNY)" },
    { value: "Colombian Peso (COP)", label: "Colombian Peso (COP)" },
    { value: "Comorian Franc (KMF)", label: "Comorian Franc (KMF)" },
    { value: "Congolese Franc (CDF)", label: "Congolese Franc (CDF)" },
    { value: "Costa Rican Colon (CRC)", label: "Costa Rican Colon (CRC)" },
    { value: "Croatian Kuna (HRK)", label: "Croatian Kuna (HRK)" },
    { value: "Cuban Peso (CUP)", label: "Cuban Peso (CUP)" },
    { value: "Czech Koruna (CZK)", label: "Czech Koruna (CZK)" },
    { value: "Danish Krone (DKK)", label: "Danish Krone (DKK)" },
    { value: "Djiboutian Franc (DJF)", label: "Djiboutian Franc (DJF)" },
    { value: "Dominican Peso (DOP)", label: "Dominican Peso (DOP)" },
    { value: "East Caribbean Dollar (XCD)", label: "East Caribbean Dollar (XCD)" },
    { value: "Egyptian Pound (EGP)", label: "Egyptian Pound (EGP)" },
    { value: "Eritrean Nakfa (ERN)", label: "Eritrean Nakfa (ERN)" },
    { value: "Estonian Kroon (EEK)", label: "Estonian Kroon (EEK)" },
    { value: "Ethiopian Birr (ETB)", label: "Ethiopian Birr (ETB)" },
    { value: "Euro (EUR)", label: "Euro (EUR)" },
    { value: "Falkland Islands Pound (FKP)", label: "Falkland Islands Pound (FKP)" },
    { value: "Fijian Dollar (FJD)", label: "Fijian Dollar (FJD)" },
    { value: "Gambian Dalasi (GMD)", label: "Gambian Dalasi (GMD)" },
    { value: "Georgian Lari (GEL)", label: "Georgian Lari (GEL)" },
    { value: "Ghanaian Cedi (GHS)", label: "Ghanaian Cedi (GHS)" },
    { value: "Gibraltar Pound (GIP)", label: "Gibraltar Pound (GIP)" },
    { value: "Guatemalan Quetzal (GTQ)", label: "Guatemalan Quetzal (GTQ)" },
    { value: "Guinean Franc (GNF)", label: "Guinean Franc (GNF)" },
    { value: "Guyanaese Dollar (GYD)", label: "Guyanaese Dollar (GYD)" },
    { value: "Haitian Gourde (HTG)", label: "Haitian Gourde (HTG)" },
    { value: "Honduran Lempira (HNL)", label: "Honduran Lempira (HNL)" },
    { value: "Hong Kong Dollar (HKD)", label: "Hong Kong Dollar (HKD)" },
    { value: "Hungarian Forint (HUF)", label: "Hungarian Forint (HUF)" },
    { value: "Icelandic Krona (ISK)", label: "Icelandic Krona (ISK)" },
    { value: "Indian Rupee (INR)", label: "Indian Rupee (INR)" },
    { value: "Indonesian Rupiah (IDR)", label: "Indonesian Rupiah (IDR)" },
    { value: "Iranian Rial (IRR)", label: "Iranian Rial (IRR)" },
    { value: "Iraqi Dinar (IQD)", label: "Iraqi Dinar (IQD)" },
    { value: "Israeli New Shekel (ILS)", label: "Israeli New Shekel (ILS)" },
    { value: "Jamaican Dollar (JMD)", label: "Jamaican Dollar (JMD)" },
    { value: "Japanese Yen (JPY)", label: "Japanese Yen (JPY)" },
    { value: "Jordanian Dinar (JOD)", label: "Jordanian Dinar (JOD)" },
    { value: "Kazakhstani Tenge (KZT)", label: "Kazakhstani Tenge (KZT)" },
    { value: "Kenyan Shilling (KES)", label: "Kenyan Shilling (KES)" },
    { value: "Kuwaiti Dinar (KWD)", label: "Kuwaiti Dinar (KWD)" },
    { value: "Kyrgyzstani Som (KGS)", label: "Kyrgyzstani Som (KGS)" },
    { value: "Laotian Kip (LAK)", label: "Laotian Kip (LAK)" },
    { value: "Latvian Lats (LVL)", label: "Latvian Lats (LVL)" },
    { value: "Lebanese Pound (LBP)", label: "Lebanese Pound (LBP)" },
    { value: "Lesotho Loti (LSL)", label: "Lesotho Loti (LSL)" },
    { value: "Liberian Dollar (LRD)", label: "Liberian Dollar (LRD)" },
    { value: "Libyan Dinar (LYD)", label: "Libyan Dinar (LYD)" },
    { value: "Lithuanian Litas (LTL)", label: "Lithuanian Litas (LTL)" },
    { value: "Macanese Pataca (MOP)", label: "Macanese Pataca (MOP)" },
    { value: "Macedonian Denar (MKD)", label: "Macedonian Denar (MKD)" },
    { value: "Malagasy Ariary (MGA)", label: "Malagasy Ariary (MGA)" },
    { value: "Malawian Kwacha (MWK)", label: "Malawian Kwacha (MWK)" },
    { value: "Malaysian Ringgit (MYR)", label: "Malaysian Ringgit (MYR)" },
    { value: "Maldivian Rufiyaa (MVR)", label: "Maldivian Rufiyaa (MVR)" },
    { value: "Mauritanian Ouguiya (MRO)", label: "Mauritanian Ouguiya (MRO)"},
    { value: "Mauritian Rupee (MUR)", label: "Mauritian Rupee (MUR)" },
    { value: "Mexican Peso (MXN)", label: "Mexican Peso (MXN)" },
    { value: "Moldovan Leu (MDL)", label: "Moldovan Leu (MDL)" },
    { value: "Mongolian Tugrik (MNT)", label: "Mongolian Tugrik (MNT)" },
    { value: "Moroccan Dirham (MAD)", label: "Moroccan Dirham (MAD)" },
    { value: "Mozambican Metical (MZN)", label: "Mozambican Metical (MZN)" },
    { value: "Myanmar Kyat (MMK)", label: "Myanmar Kyat (MMK)" },
    { value: "Namibian Dollar (NAD)", label: "Namibian Dollar (NAD)" },
    { value: "Nepalese Rupee (NPR)", label: "Nepalese Rupee (NPR)" },
    { value: "Netherlands Antillean Guilder (ANG)", label: "Netherlands Antillean Guilder (ANG)" },
    { value: "New Taiwan Dollar (TWD)", label: "New Taiwan Dollar (TWD)" },
    { value: "New Zealand Dollar (NZD)", label: "New Zealand Dollar (NZD)" },
    { value: "Nicaraguan Cordoba (NIO)", label: "Nicaraguan Cordoba (NIO)" },
    { value: "Nigerian Naira (NGN)", label: "Nigerian Naira (NGN)" },
    { value: "North Korean Won (KPW)", label: "North Korean Won (KPW)" },
    { value: "Norwegian Krone (NOK)", label: "Norwegian Krone (NOK)" },
    { value: "Omani Rial (OMR)", label: "Omani Rial (OMR)" },
    { value: "Pakistani Rupee (PKR)", label: "Pakistani Rupee (PKR)" },
    { value: "Panamanian Balboa (PAB)", label: "Panamanian Balboa (PAB)" },
    { value: "Papua New Guinean Kina (PGK)", label: "Papua New Guinean Kina (PGK)" },
    { value: "Paraguayan Guarani (PYG)", label: "Paraguayan Guarani (PYG)" },
    { value: "Peruvian Sol (PEN)", label: "Peruvian Sol (PEN)" },
    { value: "Philippine Peso (PHP)", label: "Philippine Peso (PHP)" },
    { value: "Polish Zloty (PLN)", label: "Polish Zloty (PLN)" },
    { value: "Qatari Riyal (QAR)", label: "Qatari Riyal (QAR)" },
    { value: "Romanian Leu (RON)", label: "Romanian Leu (RON)" },
    { value: "Russian Ruble (RUB)", label: "Russian Ruble (RUB)" },
    { value: "Rwandan Franc (RWF)", label: "Rwandan Franc (RWF)" },
    { value: "Saint Helenian Pound (SHP)", label: "Saint Helenian Pound (SHP)" },
    { value: "Samoan Tala (WST)", label: "Samoan Tala (WST)" },
    { value: "Sao Tomean Dobra (STN)", label: "Sao Tomean Dobra (STN)" },
    { value: "Saudi Riyal (SAR)", label: "Saudi Riyal (SAR)" },
    { value: "Serbian Dinar (RSD)", label: "Serbian Dinar (RSD)" },
    { value: "Seychellois Rupee (SCR)", label: "Seychellois Rupee (SCR)" },
    { value: "Sierra Leonean Leone (SLL)", label: "Sierra Leonean Leone (SLL)" },
    { value: "Singapore Dollar (SGD)", label: "Singapore Dollar (SGD)" },
    { value: "Solomon Islander Dollar (SBD)", label: "Solomon Islander Dollar (SBD)" },
    { value: "Somali Shilling (SOS)", label: "Somali Shilling (SOS)" },
    { value: "South African Rand (ZAR)", label: "South African Rand (ZAR)" },
    { value: "South Korean Won (KRW)", label: "South Korean Won (KRW)" },
    { value: "South Sudanese Pound (SSP)", label: "South Sudanese Pound (SSP)" },
    { value: "Sri Lankan Rupee (LKR)", label: "Sri Lankan Rupee (LKR)" },
    { value: "Sudanese Pound (SDG)", label: "Sudanese Pound (SDG)" },
    { value: "Surinamese Dollar (SRD)", label: "Surinamese Dollar (SRD)" },
    { value: "Swazi Lilangeni (SZL)", label: "Swazi Lilangeni (SZL)" },
    { value: "Swedish Krona (SEK)", label: "Swedish Krona (SEK)" },
    { value: "Swiss Franc (CHF)", label: "Swiss Franc (CHF)" },
    { value: "Syrian Pound (SYP)", label: "Syrian Pound (SYP)" },
    { value: "Taiwan New Dollar (TWD)", label: "Taiwan New Dollar (TWD)" },
    { value: "Tajikistani Somoni (TJS)", label: "Tajikistani Somoni (TJS)" },
    { value: "Tanzanian Shilling (TZS)", label: "Tanzanian Shilling (TZS)" },
    { value: "Thai Baht (THB)", label: "Thai Baht (THB)" },
    { value: "Tongan Pa'anga (TOP)", label: "Tongan Pa'anga (TOP)" },
    { value: "Trinidadian Dollar (TTD)", label: "Trinidadian Dollar (TTD)" },
    { value: "Tunisian Dinar (TND)", label: "Tunisian Dinar (TND)" },
    { value: "Turkish Lira (TRY)", label: "Turkish Lira (TRY)" },
    { value: "Turkmenistan Manat (TMT)", label: "Turkmenistan Manat (TMT)" },
    { value: "Tuvaluan Dollar (TVD)", label: "Tuvaluan Dollar (TVD)" },
    { value: "Ugandan Shilling (UGX)", label: "Ugandan Shilling (UGX)"},
    { value: "Ukrainian Hryvnia (UAH)", label: "Ukrainian Hryvnia (UAH)" },
    { value: "United Arab Emirates Dirham (AED)", label: "United Arab Emirates Dirham (AED)" },
    { value: "United States Dollar (USD)", label: "United States Dollar (USD)" },
    { value: "Uruguayan Peso (UYU)", label: "Uruguayan Peso (UYU)" },
    { value: "Uzbekistani Som (UZS)", label: "Uzbekistani Som (UZS)" },
    { value: "Vanuatu Vatu (VUV)", label: "Vanuatu Vatu (VUV)" },
    { value: "Venezuelan Bolívar (VES)", label: "Venezuelan Bolívar (VES)" },
    { value: "Vietnamese Đồng (VND)", label: "Vietnamese Đồng (VND)" },
    { value: "Wallis and Futuna CFP Franc (XPF)", label: "Wallis and Futuna CFP Franc (XPF)" },
    { value: "Yemeni Rial (YER)", label: "Yemeni Rial (YER)" },
    { value: "Zambian Kwacha (ZMW)", label: "Zambian Kwacha (ZMW)" },
    { value: "Zimbabwean Dollar (ZWL)", label: "Zimbabwean Dollar (ZWL)" }
];


export const selectOptions = [
    { value : "Web Developer", label: "Web Developer"},
    { value : "App Developer", label: "App Developer"},
    { value : "Content Writer", label: "Content Writer"},
    { value : "Graphic Designer", label: "Graphic Designer"},
    { value : "Data Analyst", label: "Data Analyst"},
    { value : "Blockchain Developer", label: "Blockchain Developer"},
];


export const planTypeOptions = [
    {value: "Per Project", label: "Per Project" },
    {value: "Per Hour", label: "Per Hour" },
    {value: "Every Day", label: "Every Day" },
    {value: "Every Week", label: "Every Week" },
    {value: "Every Month", label: "Every Month" },
    {value: "Every Quater", label: "Every Quater" },
    {value: "Every Six Months", label: "Every Six Months" },
    {value: "Every Year", label: "Every Year" },
    {value: "Every Two Year", label: "Every Two Year" },
    {value: "Every 3 Year", label: "Every 3 Year" },
    {value: "Every 5 Year", label: "Every 5 Year" },
]