export const currencyOptions = [
    { value: "Afghan Afghani (AFN)", label: "Afghan Afghani (AFN)", symbol: "؋" },
    { value: "Albanian Lek (ALL)", label: "Albanian Lek (ALL)", symbol: "L" },
    { value: "Algerian Dinar (DZD)", label: "Algerian Dinar (DZD)", symbol: "د.ج" },
    { value: "Angolan Kwanza (AOA)", label: "Angolan Kwanza (AOA)", symbol: "Kz" },
    { value: "Argentine Peso (ARS)", label: "Argentine Peso (ARS)", symbol: "$" },
    { value: "Armenian Dram (AMD)", label: "Armenian Dram (AMD)", symbol: "֏" },
    { value: "Aruban Florin (AWG)", label: "Aruban Florin (AWG)", symbol: "ƒ" },
    { value: "Australian Dollar (AUD)", label: "Australian Dollar (AUD)", symbol: "$" },
    { value: "Azerbaijani Manat (AZN)", label: "Azerbaijani Manat (AZN)", symbol: "₼" },
    { value: "Bahamian Dollar (BSD)", label: "Bahamian Dollar (BSD)", symbol: "$" },
    { value: "Bahraini Dinar (BHD)", label: "Bahraini Dinar (BHD)", symbol: "ب.د" },
    { value: "Bangladeshi Taka (BDT)", label: "Bangladeshi Taka (BDT)", symbol: "৳" },
    { value: "Barbadian Dollar (BBD)", label: "Barbadian Dollar (BBD)", symbol: "$" },
    { value: "Belarusian Ruble (BYN)", label: "Belarusian Ruble (BYN)", symbol: "Br" },
    { value: "Belize Dollar (BZD)", label: "Belize Dollar (BZD)", symbol: "BZ$" },
    { value: "Bermudan Dollar (BMD)", label: "Bermudan Dollar (BMD)", symbol: "$" },
    { value: "Bhutanese Ngultrum (BTN)", label: "Bhutanese Ngultrum (BTN)", symbol: "Nu." },
    { value: "Bolivian Boliviano (BOB)", label: "Bolivian Boliviano (BOB)", symbol: "Bs." },
    { value: "Bosnia-Herzegovina Convertible Mark (BAM)", label: "Bosnia-Herzegovina Convertible Mark (BAM)", symbol: "KM" },
    { value: "Botswanan Pula (BWP)", label: "Botswanan Pula (BWP)", symbol: "P" },
    { value: "Brazilian Real (BRL)", label: "Brazilian Real (BRL)", symbol: "R$" },
    { value: "British Pound (GBP)", label: "British Pound (GBP)", symbol: "£" },
    { value: "Brunei Dollar (BND)", label: "Brunei Dollar (BND)", symbol: "$" },
    { value: "Bulgarian Lev (BGN)", label: "Bulgarian Lev (BGN)", symbol: "лв" },
    { value: "Burundian Franc (BIF)", label: "Burundian Franc (BIF)", symbol: "FBu" },
    { value: "Cambodian Riel (KHR)", label: "Cambodian Riel (KHR)", symbol: "៛" },
    { value: "Canadian Dollar (CAD)", label: "Canadian Dollar (CAD)", symbol: "$" },
    { value: "Cape Verdean Escudo (CVE)", label: "Cape Verdean Escudo (CVE)", symbol: "$" },
    { value: "Cayman Islands Dollar (KYD)", label: "Cayman Islands Dollar (KYD)", symbol: "$" },
    { value: "Central African CFA Franc (XAF)", label: "Central African CFA Franc (XAF)", symbol: "FCFA" },
    { value: "Chilean Peso (CLP)", label: "Chilean Peso (CLP)", symbol: "$" },
    { value: "Chinese Yuan (CNY)", label: "Chinese Yuan (CNY)", symbol: "¥" },
    { value: "Colombian Peso (COP)", label: "Colombian Peso (COP)", symbol: "$" },
    { value: "Comorian Franc (KMF)", label: "Comorian Franc (KMF)", symbol: "CF" },
    { value: "Congolese Franc (CDF)", label: "Congolese Franc (CDF)", symbol: "FC" },
    { value: "Costa Rican Colón (CRC)", label: "Costa Rican Colón (CRC)", symbol: "₡" },
    { value: "Croatian Kuna (HRK)", label: "Croatian Kuna (HRK)", symbol: "kn" },
    { value: "Cuban Peso (CUP)", label: "Cuban Peso (CUP)", symbol: "$" },
    { value: "Czech Koruna (CZK)", label: "Czech Koruna (CZK)", symbol: "Kč" },
    { value: "Danish Krone (DKK)", label: "Danish Krone (DKK)", symbol: "kr" },
    { value: "Djiboutian Franc (DJF)", label: "Djiboutian Franc (DJF)", symbol: "Fdj" },
    { value: "Dominican Peso (DOP)", label: "Dominican Peso (DOP)", symbol: "RD$" },
    { value: "East Caribbean Dollar (XCD)", label: "East Caribbean Dollar (XCD)", symbol: "$" },
    { value: "Egyptian Pound (EGP)", label: "Egyptian Pound (EGP)", symbol: "£" },
    { value: "Eritrean Nakfa (ERN)", label: "Eritrean Nakfa (ERN)", symbol: "Nfk" },
    { value: "Estonian Kroon (EEK)", label: "Estonian Kroon (EEK)", symbol: "KR" },
    { value: "Ethiopian Birr (ETB)", label: "Ethiopian Birr (ETB)", symbol: "Br" },
    { value: "Euro (EUR)", label: "Euro (EUR)", symbol: "€" },
    { value: "Fijian Dollar (FJD)", label: "Fijian Dollar (FJD)", symbol: "$" },
    { value: "Gambian Dalasi (GMD)", label: "Gambian Dalasi (GMD)", symbol: "D" },
    { value: "Georgian Lari (GEL)", label: "Georgian Lari (GEL)", symbol: "₾" },
    { value: "Ghanaian Cedi (GHS)", label: "Ghanaian Cedi (GHS)", symbol: "₵" },
    { value: "Gibraltar Pound (GIP)", label: "Gibraltar Pound (GIP)", symbol: "£" },
    { value: "Guatemalan Quetzal (GTQ)", label: "Guatemalan Quetzal (GTQ)", symbol: "Q" },
    { value: "Guinean Franc (GNF)", label: "Guinean Franc (GNF)", symbol: "FG" },
    { value: "Guyanaese Dollar (GYD)", label: "Guyanaese Dollar (GYD)", symbol: "$" },
    { value: "Haitian Gourde (HTG)", label: "Haitian Gourde (HTG)", symbol: "G" },
    { value: "Honduran Lempira (HNL)", label: "Honduran Lempira (HNL)", symbol: "L" },
    { value: "Hong Kong Dollar (HKD)", label: "Hong Kong Dollar (HKD)", symbol: "$" },
    { value: "Hungarian Forint (HUF)", label: "Hungarian Forint (HUF)", symbol: "Ft" },
    { value: "Icelandic Króna (ISK)", label: "Icelandic Króna (ISK)", symbol: "kr" },
    { value: "Indian Rupee (INR)", label: "Indian Rupee (INR)", symbol: "₹" },
    { value: "Indonesian Rupiah (IDR)", label: "Indonesian Rupiah (IDR)", symbol: "Rp" },
    { value: "Iranian Rial (IRR)", label: "Iranian Rial (IRR)", symbol: "﷼" },
    { value: "Iraqi Dinar (IQD)", label: "Iraqi Dinar (IQD)", symbol: "ع.د" },
    { value: "Israeli Shekel (ILS)", label: "Israeli Shekel (ILS)", symbol: "₪" },
    { value: "Jamaican Dollar (JMD)", label: "Jamaican Dollar (JMD)", symbol: "J$" },
    { value: "Japanese Yen (JPY)", label: "Japanese Yen (JPY)", symbol: "¥" },
    { value: "Jordanian Dinar (JOD)", label: "Jordanian Dinar (JOD)", symbol: "د.ا" },
    { value: "Kazakhstani Tenge (KZT)", label: "Kazakhstani Tenge (KZT)", symbol: "₸" },
    { value: "Kenyan Shilling (KES)", label: "Kenyan Shilling (KES)", symbol: "KSh" },
    { value: "Kuwaiti Dinar (KWD)", label: "Kuwaiti Dinar (KWD)", symbol: "د.ك" },
    { value: "Kyrgystani Som (KGS)", label: "Kyrgystani Som (KGS)", symbol: "с" },
    { value: "Laotian Kip (LAK)", label: "Laotian Kip (LAK)", symbol: "₭" },
    { value: "Latvian Lats (LVL)", label: "Latvian Lats (LVL)", symbol: "Ls" },
    { value: "Lebanese Pound (LBP)", label: "Lebanese Pound (LBP)", symbol: "£" },
    { value: "Lesotho Loti (LSL)", label: "Lesotho Loti (LSL)", symbol: "L" },
    { value: "Liberian Dollar (LRD)", label: "Liberian Dollar (LRD)", symbol: "$" },
    { value: "Libyan Dinar (LYD)", label: "Libyan Dinar (LYD)", symbol: "ل.د" },
    { value: "Lithuanian Litas (LTL)", label: "Lithuanian Litas (LTL)", symbol: "Lt" },
    { value: "Macanese Pataca (MOP)", label: "Macanese Pataca (MOP)", symbol: "MOP$" },
    { value: "Macedonian Denar (MKD)", label: "Macedonian Denar (MKD)", symbol: "ден" },
    { value: "Malagasy Ariary (MGA)", label: "Malagasy Ariary (MGA)", symbol: "Ar" },
    { value: "Malawian Kwacha (MWK)", label: "Malawian Kwacha (MWK)", symbol: "MK" },
    { value: "Malaysian Ringgit (MYR)", label: "Malaysian Ringgit (MYR)", symbol: "RM" },
    { value: "Maldivian Rufiyaa (MVR)", label: "Maldivian Rufiyaa (MVR)", symbol: "Rf" },
    { value: "Mauritanian Ouguiya (MRU)", label: "Mauritanian Ouguiya (MRU)", symbol: "UM" },
    { value: "Mauritian Rupee (MUR)", label: "Mauritian Rupee (MUR)", symbol: "₨" },
    { value: "Mexican Peso (MXN)", label: "Mexican Peso (MXN)", symbol: "$" },
    { value: "Moldovan Leu (MDL)", label: "Moldovan Leu (MDL)", symbol: "L" },
    { value: "Mongolian Tugrik (MNT)", label: "Mongolian Tugrik (MNT)", symbol: "₮" },
    { value: "Moroccan Dirham (MAD)", label: "Moroccan Dirham (MAD)", symbol: "د.م." },
    { value: "Mozambican Metical (MZN)", label: "Mozambican Metical (MZN)", symbol: "MT" },
    { value: "Myanmar Kyat (MMK)", label: "Myanmar Kyat (MMK)", symbol: "K" },
    { value: "Namibian Dollar (NAD)", label: "Namibian Dollar (NAD)", symbol: "$" },
    { value: "Nepalese Rupee (NPR)", label: "Nepalese Rupee (NPR)", symbol: "₨" },
    { value: "Netherlands Antillean Guilder (ANG)", label: "Netherlands Antillean Guilder (ANG)", symbol: "ƒ" },
    { value: "New Taiwan Dollar (TWD)", label: "New Taiwan Dollar (TWD)", symbol: "NT$" },
    { value: "New Zealand Dollar (NZD)", label: "New Zealand Dollar (NZD)", symbol: "$" },
    { value: "Nicaraguan Córdoba (NIO)", label: "Nicaraguan Córdoba (NIO)", symbol: "C$" },
    { value: "Nigerian Naira (NGN)", label: "Nigerian Naira (NGN)", symbol: "₦" },
    { value: "North Korean Won (KPW)", label: "North Korean Won (KPW)", symbol: "₩" },
    { value: "Norwegian Krone (NOK)", label: "Norwegian Krone (NOK)", symbol: "kr" },
    { value: "Omani Rial (OMR)", label: "Omani Rial (OMR)", symbol: "ر.ع." },
    { value: "Pakistani Rupee (PKR)", label: "Pakistani Rupee (PKR)", symbol: "₨" },
    { value: "Panamanian Balboa (PAB)", label: "Panamanian Balboa (PAB)", symbol: "B/." },
    { value: "Papua New Guinean Kina (PGK)", label: "Papua New Guinean Kina (PGK)", symbol: "K" },
    { value: "Paraguayan Guarani (PYG)", label: "Paraguayan Guarani (PYG)", symbol: "₲" },
    { value: "Peruvian Sol (PEN)", label: "Peruvian Sol (PEN)", symbol: "S/" },
    { value: "Philippine Peso (PHP)", label: "Philippine Peso (PHP)", symbol: "₱" },
    { value: "Polish Złoty (PLN)", label: "Polish Złoty (PLN)", symbol: "zł" },
    { value: "Qatari Riyal (QAR)", label: "Qatari Riyal (QAR)", symbol: "ر.ق" },
    { value: "Romanian Leu (RON)", label: "Romanian Leu (RON)", symbol: "lei" },
    { value: "Russian Ruble (RUB)", label: "Russian Ruble (RUB)", symbol: "₽" },
    { value: "Rwandan Franc (RWF)", label: "Rwandan Franc (RWF)", symbol: "FRw" },
    { value: "Saint Helena Pound (SHP)", label: "Saint Helena Pound (SHP)", symbol: "£" },
    { value: "Samoan Tala (WST)", label: "Samoan Tala (WST)", symbol: "T" },
    { value: "Sao Tome and Principe Dobra (STN)", label: "Sao Tome and Principe Dobra (STN)", symbol: "Db" },
    { value: "Saudi Riyal (SAR)", label: "Saudi Riyal (SAR)", symbol: "ر.س" },
    { value: "Serbian Dinar (RSD)", label: "Serbian Dinar (RSD)", symbol: "дин." },
    { value: "Seychellois Rupee (SCR)", label: "Seychellois Rupee (SCR)", symbol: "₨" },
    { value: "Sierra Leonean Leone (SLL)", label: "Sierra Leonean Leone (SLL)", symbol: "Le" },
    { value: "Singapore Dollar (SGD)", label: "Singapore Dollar (SGD)", symbol: "$" },
    { value: "Solomon Islands Dollar (SBD)", label: "Solomon Islands Dollar (SBD)", symbol: "$" },
    { value: "Somali Shilling (SOS)", label: "Somali Shilling (SOS)", symbol: "S" },
    { value: "South African Rand (ZAR)", label: "South African Rand (ZAR)", symbol: "R" },
    { value: "South Korean Won (KRW)", label: "South Korean Won (KRW)", symbol: "₩" },
    { value: "South Sudanese Pound (SSP)", label: "South Sudanese Pound (SSP)", symbol: "£" },
    { value: "Sri Lankan Rupee (LKR)", label: "Sri Lankan Rupee (LKR)", symbol: "₨" },
    { value: "Sudanese Pound (SDG)", label: "Sudanese Pound (SDG)", symbol: "ج.س." },
    { value: "Surinamese Dollar (SRD)", label: "Surinamese Dollar (SRD)", symbol: "$" },
    { value: "Swazi Lilangeni (SZL)", label: "Swazi Lilangeni (SZL)", symbol: "L" },
    { value: "Swedish Krona (SEK)", label: "Swedish Krona (SEK)", symbol: "kr" },
    { value: "Swiss Franc (CHF)", label: "Swiss Franc (CHF)", symbol: "Fr." },
    { value: "Syrian Pound (SYP)", label: "Syrian Pound (SYP)", symbol: "£" },
    { value: "Tajikistani Somoni (TJS)", label: "Tajikistani Somoni (TJS)", symbol: "ЅМ" },
    { value: "Tanzanian Shilling (TZS)", label: "Tanzanian Shilling (TZS)", symbol: "TSh" },
    { value: "Thai Baht (THB)", label: "Thai Baht (THB)", symbol: "฿" },   
    { value: "Tongan Pa'anga (TOP)", label: "Tongan Pa'anga (TOP)", symbol: "T$" },
    { value: "Trinidad and Tobago Dollar (TTD)", label: "Trinidad and Tobago Dollar (TTD)", symbol: "TT$" },
    { value: "Tunisian Dinar (TND)", label: "Tunisian Dinar (TND)", symbol: "د.ت" },
    { value: "Turkish Lira (TRY)", label: "Turkish Lira (TRY)", symbol: "₺" },
    { value: "Turkmenistani Manat (TMT)", label: "Turkmenistani Manat (TMT)", symbol: "m" },
    { value: "Ugandan Shilling (UGX)", label: "Ugandan Shilling (UGX)", symbol: "USh" },
    { value: "Ukrainian Hryvnia (UAH)", label: "Ukrainian Hryvnia (UAH)", symbol: "₴" },
    { value: "United Arab Emirates Dirham (AED)", label: "United Arab Emirates Dirham (AED)", symbol: "د.إ" },
    { value: "United States Dollar (USD)", label: "United States Dollar (USD)", symbol: "$" },
    { value: "Uruguayan Peso (UYU)", label: "Uruguayan Peso (UYU)", symbol: "$U" },
    { value: "Uzbekistani Som (UZS)", label: "Uzbekistani Som (UZS)", symbol: "лв" },
    { value: "Vanuatu Vatu (VUV)", label: "Vanuatu Vatu (VUV)", symbol: "VT" },
    { value: "Venezuelan Bolívar (VES)", label: "Venezuelan Bolívar (VES)", symbol: "Bs" },
    { value: "Vietnamese Đồng (VND)", label: "Vietnamese Đồng (VND)", symbol: "₫" },
    { value: "Yemeni Rial (YER)", label: "Yemeni Rial (YER)", symbol: "﷼" },
    { value: "Zambian Kwacha (ZMW)", label: "Zambian Kwacha (ZMW)", symbol: "ZK" },
    { value: "Zimbabwean Dollar (ZWL)", label: "Zimbabwean Dollar (ZWL)", symbol: "Z$" }
];
  

export const selectOptions = [
    { value : "Web Developer", label: "Web Developer"},
    { value : "App Developer", label: "App Developer"},
    { value : "Content Writer", label: "Content Writer"},
    { value : "Graphic Designer", label: "Graphic Designer"},
    { value : "Data Analyst", label: "Data Analyst"},
    { value : "Blockchain Developer", label: "Blockchain Developer"},
];


export const planTypeOptions = [
    {value: "Per Project", label: "Per Project" },
    {value: "Per Hour", label: "Per Hour" },
    {value: "Every Day", label: "Every Day" },
    {value: "Every Week", label: "Every Week" },
    {value: "Every Month", label: "Every Month" },
    {value: "Every Quater", label: "Every Quater" },
    {value: "Every Six Months", label: "Every Six Months" },
    {value: "Every Year", label: "Every Year" },
    {value: "Every Two Year", label: "Every Two Year" },
    {value: "Every 3 Year", label: "Every 3 Year" },
    {value: "Every 5 Year", label: "Every 5 Year" },
]