
GET http://localhost:3001/quotation


























# GET http://localhost:3001/service
###############3
GET http://localhost:3001/upload

################################


######################
POST http://localhost:3001/new/quotation
Content-Type: application/json

{
  "quotation_no": "TEST7",
  "quotation_date": "2023-05-22",
  "q_top_add_more_field": [
    {
      "fieldName": "Top Field 1",
      "value": "Value 1"
    },
    {
      "fieldName": "Top Field 2",
      "value": "Value 2"
    }
  ],
  "business_details": {
    "your_business": {
      "name": "Your Business Name",
      "address": "Your Business Address"
    },
    "client": {
      "name": "Client Name",
      "address": "Client Address"
    }
  },
  "gst": {
    "tax_type": "GST",
    "gst_type": "IGST"
  },
  "currency": {
    "short_form": "INR",
    "symbol": "₹"
  },
  "number_format": {
    "format": "lakhs",
    "decimal_digits": "2"
  },
  "table": [
    {
      "key": "0",
      "Item": "Television",
      "Quantity": "2",
      "Rate": "₹ 1000",
      "Amount": "₹ 2000"
    },
    {
      "key": "1",
      "Item": "Laptop",
      "Quantity": "1",
      "Rate": "₹ 500",
      "Amount": "₹ 500"
    }
  ],
  "item_wise_discount": {
    "discount": {
      "discount_type": "Percentage",
      "discount_value": "10"
    },
    "subtotal": "₹ 2500",
    "amount": "₹ 2250"
  },
  "hideTotals": {
    "discount_on_total": {
      "key": "Reduction",
      "value": "2",
      "discount_type": "%"
    },
    "additional_charges": {
      "key": "Extra charges",
      "value": "100",
      "discount_type": "₹"
    },
    "total": "₹ 2150",
    "total_in_words": "Two Thousand One Hundred Fifty Rupees"
  },
  "q_bottom_add_more_field": [
    {
      "fieldName": "Bottom Field 1",
      "value": "Value 1"
    },
    {
      "fieldName": "Bottom Field 2",
      "value": "Value 2"
    }
  ],
  "terms_and_conditions": [
    {
      "id": "1",
      "value": "Applicable taxes will be extra."
    },
    {
      "id": "2",
      "value": "Work will resume after advance payment."
    }
  ],
  "notes": "This is a note...",
  "additional_info": [
    {
      "key": "Additional Info 1",
      "value": "Value 1"
    },
    {
      "key": "Additional Info 2",
      "value": "Value 2"
    }
  ],
  "contact_info": {
    "email": "example@example.com",
    "phone": "1234567890"
  }
}



# ###############
# GET http://localhost:3001/service/645a197c2ef3c33ed1e150ab

# ##########################

# PUT http://localhost:3001/editservice/645a3c15c49b776d36375114


# ################

# POST http://localhost:3001/new/service
# Content-Type: application/json

# {
#     "service_name": "Pole Dancer",
#      "service_para": "Hii!! Please Hire me",
#      "service_tags": ["Creator", "Copywriter","Filming & Shooting"],
#      "isPricing": true,
#      "pricing": {
#        "service_currency": "Indian Rupees",
#        "service_amount": 100,
#        "service_plan_type": "Every Week",
#        "isPriceRange": true,
#        "min_amount": 50,
#        "max_amount": 100,
#        "isDiscountPrice": true,
#        "pre_discount_price": 199
#      }
# }

# #######################
# DELETE http://localhost:3001/service/645a23fb327f9ac994e5d9c0
